---
- hosts: localhost
  roles:
  - { role: network-checks }
  gather_facts: no  
  vars:
  - control_plane_lb_ip: "10.0.0.10"
  - apps_lb_ip: "10.0.0.10"
  - base_name: "rhbr-labs.com"
  - cluster_name: "ocp"