---
- fail:
    msg: "{{ hostvars['cloud'] }}"

- name: Check A records for servers
  command: "dig {{ item }} +short"
  loop: "{{ groups['all'] }}"
  register: check_a_records_servers

- name: Check PTR records for servers
  command: "dig -x {{ hostvars[item]['ansible_host'] }} +short"
  loop: "{{ groups['all'] }}"
  register: check_ptr_records_servers
  when: "'etcd' not in hostvars[item]['group_names']"    

- name: Check A records for API and APPS
  command: "dig {{ item }} +short"
  loop: 
    - "{{ hostvars[0]['api_url'] }}"
    - "api-int.{{zone_name}}"
    - "*.apps.{{zone_name}}"
  register: check_api_records_servers

- name: Check SRV records
  command: "dig {{ item }} +short"
  loop: 
    - "_etcd-server-ssl._tcp.{{zone_name}} SRV +short"
  register: check_srv_record

- name: delete temp file if exists
  file:
    dest: /tmp/checks-output.txt
    state: absent
  delegate_to: localhost    

- name: create temp file
  file:
    dest: /tmp/checks-output.txt
    state: touch
  delegate_to: localhost

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "*** Check A records *****\n"
    insertafter: EOF
  delegate_to: localhost

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "A record for {{item.item}} = {{item.stdout}} --> RESULT: {% if item.stdout == hostvars[item.item]['ansible_host'] %} SUCCESS! {% else %} FAILED! {% endif %}"
    insertafter: EOF
  delegate_to: localhost
  loop: "{{ check_a_records_servers.results }}"  
  when: "'etcd' not in hostvars[item.item]['group_names']"  

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "\n*** Check PTR records *****\n"
    insertafter: EOF
  delegate_to: localhost

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "PTR record for {{item.item}}/{{ hostvars[item.item]['ansible_host'] }} = {{item.stdout}} --> RESULT: {% if item.item in item.stdout %} SUCCESS! {% else %} FAILED! {% endif %}"
    insertafter: EOF
  delegate_to: localhost
  loop: "{{ check_ptr_records_servers.results }}"  
  when: "'etcd' not in hostvars[item.item]['group_names']"  

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "\n*** Check API/APPs records *****\n"
    insertafter: EOF
  delegate_to: localhost

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "API/APPs record for {{item.item}}/{{ hostvars[item.item]['ansible_host'] }} = {{item.stdout}} --> RESULT: {% if item.item in item.stdout %} SUCCESS! {% else %} FAILED! {% endif %}"
    insertafter: EOF
  delegate_to: localhost
  loop: "{{ check_ptr_records_servers.results }}"  
  when: "'etcd' not in hostvars[item.item]['group_names']"    