---
- name: Check A records for servers
  command: "dig {{ item }} +short"
  loop: "{{ groups['all'] }}"
  register: check_a_records_servers

- name: Check PTR records for servers
  command: "dig -x {{ hostvars[item]['ansible_host'] }} +short"
  loop: "{{ groups['all'] }}"
  register: check_ptr_records_servers
  when: "'etcd' not in hostvars[item]['group_names']"    

- name: Check A records for API
  command: "dig {{ item }} +short"
  loop: 
    - "{{ api_url }}"
    - "{{ api_int_url }}"
  register: check_api_records_servers

- name: Check A records for APPS
  command: "dig {{ item }} +short"
  loop: 
    - "{{ apps_wildcard }}"
  register: check_apps_records_servers  

- name: Check SRV records
  command: "dig {{ item }} +short"
  loop: 
    - "_etcd-server-ssl._tcp.{{cluster_name}}.{{base_name}} SRV +short"
  register: check_srv_record

- name: delete temp file if exists
  file:
    dest: /tmp/checks-output.txt
    state: absent
  delegate_to: localhost    

- name: create temp file
  file:
    dest: /tmp/checks-output.txt
    state: touch
  delegate_to: localhost

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "*** Check A records *****\n"
    insertafter: EOF
  delegate_to: localhost

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "A record for {{item.item}} = {{item.stdout}} --> RESULT: {% if item.stdout == hostvars[item.item]['ansible_host'] %} SUCCESS! {% else %} FAILED! {% endif %}"
    insertafter: EOF
  delegate_to: localhost
  loop: "{{ check_a_records_servers.results }}"  
  when: "'etcd' not in hostvars[item.item]['group_names']"  

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "\n*** Check PTR records *****\n"
    insertafter: EOF
  delegate_to: localhost

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "PTR record for {{item.item}}/{{ hostvars[item.item]['ansible_host'] }} = {{item.stdout}} --> RESULT: {% if item.item in item.stdout %} SUCCESS! {% else %} FAILED! {% endif %}"
    insertafter: EOF
  delegate_to: localhost
  loop: "{{ check_ptr_records_servers.results }}"  
  when: "'etcd' not in hostvars[item.item]['group_names']"  

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "\n*** Check API/APPs records *****\n"
    insertafter: EOF
  delegate_to: localhost

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "API record for {{item.item}} = {{item.stdout}} --> RESULT: {% if item.stdout == control_plane_lb_ip %} SUCCESS! {% else %} FAILED! {% endif %}"
    insertafter: EOF
  delegate_to: localhost
  loop: "{{ check_api_records_servers.results }}"   

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "APPS wildcard record for {{item.item}} = {{item.stdout}} --> RESULT: {% if item.stdout == apps_lb_ip %} SUCCESS! {% else %} FAILED! {% endif %}"
    insertafter: EOF
  delegate_to: localhost
  loop: "{{ check_apps_records_servers.results }}"   


##### CHECKING SRV RECORDS

- name: Define SRV records template
  template:
    src: etcd-srv-records.j2
    dest: /tmp/etcd-srv-records-tmpl.txt

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "\n*** Check SRV record *****\n"
    insertafter: EOF
  delegate_to: localhost

- name: append
  lineinfile:
    dest: /tmp/checks-output.txt
    line: "SRV record for {{item.item}} --> RESULT: {% if item.stdout | sort() == lookup('file', '/tmp/etcd-srv-records-tmpl.txt') | sort() %} SUCCESS! {% else %} FAILED! {% endif %}"
    insertafter: EOF
  delegate_to: localhost
  loop: "{{ check_srv_record.results }}"  
 
- name: SHOW RESULTS
  debug:
    msg: "{{ lookup('file', '/tmp/checks-output.txt') }}"
