---
- name: Check A records for servers
  command: "dig {{ item }} +short"
  loop: "{{ groups['all'] }}"
  register: check_a_records_servers

#- name: Populate results dictionary for server A records
#  set_fact:
#    servers_a_records: "{{ servers_a_records|default({}) | combine( {item.item: item.stdout} ) }}"
#  loop: "{{ check_a_records_servers.results }}"

- name: Initialize result string
  set_fact:
    check_dns_result: "*** Check A records *****"

- name: Populate results dictionary for server A records
  set_fact:
    check_dns_result: "{{ check_dns_result|default() | 'A record for {item.item} = {item.stdout} --> RESULT: { item.stdout == hostvars[item]['ansible_host'] }' }}"
  loop: "{{ check_a_records_servers.results }}"

- name: copy the output to a local file
  copy:
    content: "{{ set_fact.stdout }}"
    dest: "/tmp/checks-output.txt"
  delegate_to: localhost

- name: result A servers
  debug: 
    msg: "{{ servers_a_records }}"

- name: PTR
  debug:
    msg: "{{ hostvars[item]['ansible_host'] }}"
  loop: "{{ groups['all'] }}"
  when: "'etcd' not in hostvars[item]['group_names']"

- name: Check PTR records for servers
  command: "dig -x {{ hostvars[item]['ansible_host'] }} +short"
  loop: "{{ groups['all'] }}"
  register: check_ptr_records_servers
  when: "'etcd' not in hostvars[item]['group_names']"    

- name: Populate results dictionary for server PTR records
  set_fact:
    servers_ptr_records: "{{ servers_ptr_records|default({}) | combine( {item.item: item.stdout} ) }}"
  loop: "{{ check_ptr_records_servers.results }}"
  when: item is not skipped

- name: result PTR servers
  debug: 
    msg: "{{ servers_ptr_records }}"  

- name: Check A records for API and APPS
  command: "dig {{ item }} +short"
  loop: 
    - "api.{{zone_name}}"
    - "api-int.{{zone_name}}"
    - "*.apps.{{zone_name}}"
  register: check_api_records_servers

- name: Populate results dictionary for api and APPS A records
  set_fact:
    api_a_records: "{{ api_a_records|default({}) | combine( {item.item: item.stdout} ) }}"
  loop: "{{ check_api_records_servers.results }}"
  when: item is not skipped

- name: Check SRV records
  command: "dig {{ item }} +short"
  loop: 
    - "_etcd-server-ssl._tcp.{{zone_name}} SRV +short"
  register: check_srv_record

- name: Populate results dictionary for SRV records
  set_fact:
    etcd_srv_records: "{{ etcd_srv_records|default({}) | combine( {item.item: item.stdout} ) }}"
  loop: "{{ check_srv_record.results }}"
  when: item is not skipped

- name: Check SRV records
  debug: 
    msg: "{{ etcd_srv_records }}"    