---
# tasks file for ocp-prepare-prereqs

- name: Check if /etc/named.conf already exists
  tags: conf_dns
  stat:
    path: /etc/named.conf
  register: named_exists  

- name: Create named.conf if not exists
  tags: conf_dns
  file:
    dest: /etc/named.conf
    owner: root
    group: root
    mode: '0755'    
    state: touch
  when: named_exists.stat.exists == False 

- blockinfile:
    dest: /etc/named.conf
    block: "{{ lookup('template', 'named.j2') }}"     
    marker: "/* rhbr-labs.com zone */"    

- name: Check if /var/lib/{{zone_name}}.zone already exists
  tags: conf_dns
  stat:
    path: /var/named/{{zone_name}}.zone
  register: named_exists  

- name: Create /var/lib/{{zone_name}}.zone if not exists
  tags: conf_dns
  file:
    dest: /var/named/{{zone_name}}.zone
    owner: root
    group: root
    mode: '0755'    
    state: touch
  when: named_exists.stat.exists == False 

- blockinfile: 
    dest: /var/named/{{zone_name}}.zone
    block: "{{ lookup('template', 'dns-zone.j2') }}"
    marker: "/* rhbr-labs.com zone */"        

- name: Check if /var/named/{{reverse_zone_name}}.zone already exists
  tags: conf_dns
  stat:
    path: /var/named/{{reverse_zone_name}}.zone
  register: named_exists  

- name: Create /var/named/{{reverse_zone_name}}.zone if not exists
  tags: conf_dns
  file:
    dest: /var/named/{{reverse_zone_name}}.zone
    owner: root
    group: root
    mode: '0755'    
    state: touch
  when: named_exists.stat.exists == False 

- blockinfile:  
    dest: /var/named/{{reverse_zone_name}}.zone
    block: "{{ lookup('template', 'dns-reverse-zone.j2') }}"
    marker: "/* rhbr-labs.com zone */"        

- name: Restart and enable dns-server
  systemd:
    state: restarted
    enabled: yes    
    daemon_reload: yes
    name: named-chroot 

- name: Configure firewalld services
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled      
  with_items:
    - dns
